### ISSUE TITLE
Obviate the need for the molecule-notest tag

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-xfce-cool#29]
# 💡 Summary #

In this role we apply the `molecule-notest` tag to the Ansible task that actually enables the user-mode `systemd` service.  We do this because I was unable to find a way to write this task in such a way that it would succeed when run via `molecule` (utilizing Docker) _and_ when run against an actual AWS instance (i.e. when used to create an AMI).  It would be far better to find a way to make the same code succeed under both conditions.

## Motivation and context ##

If the same code succeeds in both cases then we can test it via `molecule`.

## Implementation notes ##

The `test_symlink_exists` `molecule` test should be uncommented once this issue is resolved.

[It should be possible to achieve this using `become_method: machinectl`](https://docs.ansible.com/ansible/latest/user_guide/become.html#may-not-access-environment-variables-populated-by-pamd-systemd), but I haven't been able to get that to work either.

This is the way to write the task such that it succeeds when run via `molecule`:
```yml
- name: >-
    Enable the user-mode systemd service that creates the file share symlink
    for the user
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: create-fileshare-symlink
    scope: user
  become: no
  tags:
    - molecule-idempotence-notest
  vars:
    # We have to ssh in as the actual user for whom we are enabling
    # the service.  sshing in as root and becoming the user is not
    # sufficient to set all the environment variables that we need.
    ansible_ssh_user: "{{ username }}"
```
